---
extends:
  - plugin:vue/vue3-essential
  - "@vue/eslint-config-airbnb-with-typescript"
  - "@vue/eslint-config-airbnb-with-typescript/allow-js-in-vue"
  - prettier # this (eslint-config-prettier) disables rules that would conflict with Prettier
plugins:
  - unused-imports
ignorePatterns:
  - node_modules/*
  - .nuxt/*
rules:
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  camelcase: 0
  comma-dangle:
    - error
    - always-multiline
  no-restricted-syntax: 0 # we don't invest in IE11 testing
  no-use-before-define: 0 # a good one, but broken linter
  no-param-reassign:
    - error
    - props: false
  import/no-cycle: 0 # a good one, but broken linter
  import/no-extraneous-dependencies: 0 # not applicable
  no-shadow: 0 # a good one, but broken linter
  no-empty-function: 0 # a good one, but broken linter
  no-useless-constructor: 0 # a good one, but broken linter
  no-console: 0 # not applicable
  consistent-return: 0 # a good one, but broken linter
  object-shorthand: 0 # shorthand works poorly with pycharm
  operator-linebreak: 0 # a good one, but broken linter
  object-curly-newline: 0 # a good one, but broken linter
  no-unused-vars: 0 # a good one, but many exceptions + broken linter
  typescript-eslint/no-unused-vars: 0
  no-underscore-dangle: 0 # not applicable
  prefer-destructuring: 0 # poor code style
  max-classes-per-file: 0 # why?
  no-inner-declarations: 0
  lines-between-class-members: 0 # picky. TS
  import/prefer-default-export: 0
  import/extensions: 0
  no-continue: 0 # fights my personal strong pref for left-aligned happy path.
  unused-imports/no-unused-imports: 2
  typescript-eslint/dot-notation: 0 # doesn't matter
  vue/no-v-text-v-html-on-component: 0 # we need this
  vue/multi-word-component-names: 0 # "index.vue", "about.vue"...
env:
  browser: true
  node: true
globals:
  gtag: true
  google: true
  JSX: true
