import { defineNuxtPlugin } from "#app";
import { addIcons } from "oh-vue-icons";
import {
  BiGithub,
  HiSolidExternalLink,
  MdStarrateRound,
  BiQuestionCircleFill,
  RiExternalLinkLine,
  FaMapMarkerAlt,
  IoLocationOutline,
  IoInformationCircle,
  BiThreeDots,
  HiSolidPlus,
  MdAddcircleoutlineRound,
  HiChevronDown,
  RiArrowDownSFill,
  OiEye,
  MdFilterlistRound,
  IoClose,
  IoMenu,
  MdAddalertRound,
  IoSearch,
  RiChat4Line,
  RiShareBoxFill,
} from "oh-vue-icons/icons";

export default defineNuxtPlugin((nuxtApp) => {
  addIcons(
    BiGithub,
    HiSolidExternalLink,
    MdStarrateRound,
    BiQuestionCircleFill,
    RiExternalLinkLine,
    FaMapMarkerAlt,
    IoLocationOutline,
    BiThreeDots,
    HiSolidPlus,
    MdAddcircleoutlineRound,
    HiChevronDown,
    IoInformationCircle,
    RiArrowDownSFill,
    OiEye,
    MdFilterlistRound,
    IoClose,
    IoMenu,
    MdAddalertRound,
    IoSearch,
    RiChat4Line,
    RiShareBoxFill,
  );
});
